### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lilbee717** [ashrafulsarkar/first-order-coupon-manager-for-woocommerce#19]
Hi sir, I've got email from Wordpress that tell me my website has a technical issue. In error detail, it pointing to line 60.
Here is the detail: 
An error of type E_PARSE was caused in line 60 of the file /home/pleucoid/public_html/wp-content/plugins/first-order-coupon-manager-for-woocommerce/first-order-coupon-manager-for-woocommerce.php. Error message: syntax error, unexpected ')'
Could you help me to fix this

**Comment by ashrafulsarkar** [comment]
please try our updated version: https://wordpress.org/plugins/first-order-coupon-manager-for-woocommerce/
